#!/bin/bash
set -e

CALIBRE_ROOT=${CALIBRE_ROOT:-"/Applications/calibre.app/Contents/MacOS"}

print-usage() {
    echo "Usage: generate-thumbnails <path>"
    exit 1
}

get-uuid() {
    local AZW3_FILE="$1"
    "$CALIBRE_ROOT/ebook-meta" "$AZW3_FILE" | grep -Eo 'mobi-asin:(.+)' | cut -d: -f2
}

get-cover() {
    local AZW3_FILE="$1"
    local OUTDIR="${2:-$(dirname "$AZW3_FILE"})}"
    local COVER="$OUTDIR/thumbnail_$(get-uuid "$AZW3_FILE")_EBOK_portrait.jpg"
    "$CALIBRE_ROOT/ebook-meta" "$AZW3_FILE" --get-cover "$COVER" > /dev/null
    magick mogrify -resize 169x240 -colorspace Gray "$COVER"
    echo "Processed $(basename "$AZW3_FILE")"
}


if [ -z "$1" ]; then
    print-usage
fi

if [ -d "$1" ]; then
    ROOT="$1"
    while IFS= read -d '' f; do
        get-cover "$f" "$ROOT"
    done < <(find "$ROOT" -type f -name "*.azw3" -print0)
elif [ -f "$1" ]; then
    get-cover "$1"
else
    echo "ENOENT $1"
fi
